name: Safari
on: [push]
jobs:
  safaridriver:
    runs-on: macos-14
    steps:
      - run: ps aux

      - run: |
          curl https://gist.githubusercontent.com/jrmuizel/92d3e045313ea09454907df2a9015199/raw/d9a029ad43a3596adfeb70376886d373570a21ba/test.c > /tmp/test.c;
          clang /tmp/test.c -o /tmp/test;
          /tmp/test;
          ls ~/Library/LaunchAgents
          cat ~/Library/LaunchAgents/runner-provisioner.plist
          cat /usr/local/opt/runner/runprovisioner.sh
      - run: brew install pstree
      - run: pstree
      #- run: safaridriver --diagnose
